"""Add extended CSV fields

Revision ID: 7e8fd24f44ef
Revises: 
Create Date: 2026-06-06 10:45:16.572660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e8fd24f44ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blood_requests', sa.Column('external_id', sa.String(), nullable=True))
    op.add_column('blood_requests', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('blood_requests', sa.Column('bridge_id', sa.String(), nullable=True))
    op.add_column('blood_requests', sa.Column('role_status', sa.Boolean(), nullable=True))
    op.add_column('blood_requests', sa.Column('bridge_status', sa.Boolean(), nullable=True))
    op.add_column('blood_requests', sa.Column('bridge_gender', sa.String(), nullable=True))
    op.add_column('blood_requests', sa.Column('bridge_blood_group', sa.String(), nullable=True))
    op.add_column('blood_requests', sa.Column('last_transfusion_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('blood_requests', sa.Column('expected_next_transfusion_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('blood_requests', sa.Column('status_of_bridge', sa.Boolean(), nullable=True))
    op.add_column('blood_requests', sa.Column('last_bridge_donation_date', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_blood_requests_external_id'), 'blood_requests', ['external_id'], unique=True)
    op.add_column('users', sa.Column('external_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('users', sa.Column('registration_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('donor_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_contacted_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('next_eligible_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('donations_till_date', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('eligibility_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cycle_of_donations', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('total_calls', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('frequency_in_days', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('account_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('donated_earlier', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('calls_to_donations_ratio', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('user_donation_active_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('inactive_trigger_comment', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.drop_column('users', 'inactive_trigger_comment')
    op.drop_column('users', 'user_donation_active_status')
    op.drop_column('users', 'calls_to_donations_ratio')
    op.drop_column('users', 'donated_earlier')
    op.drop_column('users', 'account_status')
    op.drop_column('users', 'frequency_in_days')
    op.drop_column('users', 'total_calls')
    op.drop_column('users', 'cycle_of_donations')
    op.drop_column('users', 'eligibility_status')
    op.drop_column('users', 'donations_till_date')
    op.drop_column('users', 'next_eligible_date')
    op.drop_column('users', 'last_contacted_date')
    op.drop_column('users', 'donor_type')
    op.drop_column('users', 'registration_date')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'external_id')
    op.drop_index(op.f('ix_blood_requests_external_id'), table_name='blood_requests')
    op.drop_column('blood_requests', 'last_bridge_donation_date')
    op.drop_column('blood_requests', 'status_of_bridge')
    op.drop_column('blood_requests', 'expected_next_transfusion_date')
    op.drop_column('blood_requests', 'last_transfusion_date')
    op.drop_column('blood_requests', 'bridge_blood_group')
    op.drop_column('blood_requests', 'bridge_gender')
    op.drop_column('blood_requests', 'bridge_status')
    op.drop_column('blood_requests', 'role_status')
    op.drop_column('blood_requests', 'bridge_id')
    op.drop_column('blood_requests', 'gender')
    op.drop_column('blood_requests', 'external_id')
    # ### end Alembic commands ###
